import { palette, rgba } from './colors';

export const darkTheme = {
  mode: 'dark',
  colors: {
    background: palette.slate950,
    surface: palette.slate900,
    surfaceSecondary: palette.slate800,
    surfaceElevated: '#202632',
    primary: '#7AB7FF',
    primaryLight: palette.blue700,
    primaryDark: palette.blue800,
    accent: palette.green300,
    accentLight: '#20351F',
    accentDark: palette.green500,
    text: '#F0F4FA',
    textSecondary: palette.slate300,
    textMuted: '#8390A3',
    textOnPrimary: palette.slate950,
    textOnAccent: palette.slate950,
    error: palette.red400,
    errorLight: '#3D1A1A',
    warning: palette.amber300,
    success: palette.green300,
    info: '#7AB7FF',
    border: palette.slate700,
    borderLight: palette.slate800,
    overlay: rgba.scrimDark,
    overlayLight: rgba.pressedDark,
    focus: '#9CCBFF',
    white: palette.white,
    black: '#000000',
  },
  shadows: {
    sm: { shadowColor: '#000000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.24, shadowRadius: 2, elevation: 2 },
    md: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.32, shadowRadius: 4, elevation: 4 },
    lg: { shadowColor: '#000000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 8, elevation: 8 },
  },
};
