import { palette, rgba } from './colors';

export const lightTheme = {
  mode: 'light',
  colors: {
    background: palette.slate100,
    surface: palette.white,
    surfaceSecondary: palette.slate50,
    surfaceElevated: palette.white,
    primary: palette.blue800,
    primaryLight: palette.blue100,
    primaryDark: palette.blue900,
    accent: palette.green500,
    accentLight: palette.green100,
    accentDark: palette.green700,
    text: palette.ink,
    textSecondary: palette.slate500,
    textMuted: palette.slate400,
    textOnPrimary: palette.white,
    textOnAccent: palette.white,
    error: palette.red600,
    errorLight: palette.red100,
    warning: palette.amber500,
    success: palette.green500,
    info: palette.blue800,
    border: '#E0E4E8',
    borderLight: '#F0F1F3',
    overlay: rgba.scrimLight,
    overlayLight: rgba.pressedLight,
    focus: palette.blue700,
    white: palette.white,
    black: '#000000',
  },
  shadows: {
    sm: { shadowColor: '#000000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 2, elevation: 1 },
    md: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.12, shadowRadius: 4, elevation: 3 },
    lg: { shadowColor: '#000000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8, elevation: 5 },
  },
};
